/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 19-dic-2010, 14:27:56
 */

package javaappdb;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdom.*;
import java.io.*;
import java.util.*;
import org.jdom.input.*;
import org.jdom.output.*;
import com.mysql.jdbc.*;
import java.sql.Connection;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILY
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    private CConexion obj;
    public NewJFrame() {
        obj=new CConexion();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor a XML");
        setResizable(false);
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame1.setTitle("Crear Conexi\u00f3n.");
        jInternalFrame1.setName("");
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jInternalFrame1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jInternalFrame1ComponentHidden(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Nombre de Usuario:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Contrase\u00f1a:");

        jButton1.setText("Insertar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Puerto:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Servidor:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jInternalFrame1.setBounds(10, 30, 300, 240);
        jDesktopPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame2.setTitle("Conversi\u00f3n");
        jInternalFrame2.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame2InternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jInternalFrame2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jInternalFrame2ComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jInternalFrame2ComponentShown(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(51, 0, 51));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Convertidor a XML", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 0, 0)));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane1.setBounds(10, 30, 590, 340);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Convertir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar");
        jButton5.setEnabled(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        jButton6.setText("Atr\u00e1s");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3)
                        .addGap(98, 98, 98)
                        .addComponent(jButton5)
                        .addGap(115, 115, 115)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jInternalFrame2.setBounds(20, 10, 640, 467);
        jDesktopPane1.add(jInternalFrame2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame3.setClosable(true);
        jInternalFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame3.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame3InternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jInternalFrame3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jInternalFrame3ComponentHidden(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Nombre de la base de Datos:");

        jButton4.setText("Seleccionar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 132, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(111, 111, 111))))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(27, 27, 27))
        );
        jInternalFrame3.setBounds(110, 30, 340, 190);
        jDesktopPane1.add(jInternalFrame3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Conexi\u00f3n");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu1MouseReleased(evt);
            }
        });

        jMenuItem1.setText("Insertar datos");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Conversi\u00f3n");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseReleased(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
// TODO add your handling code here:
        JFileChooser f=new JFileChooser();
        f.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("XML","xml");
        f.setFileFilter(filtro);
        int x=f.showSaveDialog(jLabel1);
        if(x==JFileChooser.APPROVE_OPTION)
        {
            try{
            //String leer=jTextArea1.getText();
            //File fi= f.getCurrentDirectory() + "\\" + f.getSelectedFile();
            File fi= new File(f.getSelectedFile().getAbsolutePath() + ".xml");
            FileOutputStream fis = new FileOutputStream(fi);
            FileWriter fichero=new FileWriter(fi,false);
            PrintWriter pw = new PrintWriter(fichero);
           
            //DataInputStream dis = new DataInputStream(fis);
            String lee="";
           pw.print(jTextArea1.getText());
            }catch( Exception e)
                  {
                   System.err.println("Error"+e.getMessage());
                  }            
        }
    }//GEN-LAST:event_jButton5MouseReleased

    private void jInternalFrame1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jInternalFrame1ComponentHidden
  jMenu1.setEnabled(true);
    }//GEN-LAST:event_jInternalFrame1ComponentHidden

    private void jInternalFrame1InternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1InternalFrameActivated
        // TODO add your handling code here:
        jMenu1.setEnabled(false);
    }//GEN-LAST:event_jInternalFrame1InternalFrameActivated



    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        // TODO add your handling code here:


    String nom=jTextField1.getText().replace(" ","");
    String con=jPasswordField1.getText().replace(" ","");
    String p=jTextField2.getText().replace(" ","");
    
    String serv=jTextField3.getText().replace(" ","");
    String bd="bb";//jTextField4.getText().replace(" ","");

    try{
        obj.EBlanco(nom, con, p, bd, serv);
    int puerto=Integer.parseInt(p);
    obj.setnomU(nom);
    obj.setcont(con);
    obj.setPuer(puerto);
    obj.setnomBD(bd);
    obj.setServ(serv);
    obj.Conectar();
   java.sql.Statement st11 = obj.getCon().createStatement();
    java.sql.ResultSet rs11 = st11.executeQuery("Show Databases ");
    java.sql.ResultSetMetaData rsmd11=rs11.getMetaData();
       if(rs11.first()==true)
       {
           String gg=rsmd11.getColumnName(1);
             do{
                String nnbbdd=rs11.getString(gg);
                jComboBox1.addItem(nnbbdd);
               }while(rs11.next()==true);

       }else System.out.print("NO HAY DATOS EN LA TABLA");
    
    jTextField1.setText("");
    jPasswordField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    //jTextField4.setText("");
    jMenuItem2.setEnabled(true);
    //jInternalFrame2.setVisible(true);
    jInternalFrame3.setVisible(true);
    jInternalFrame1.setVisible(false);
    }
    catch(EspaciosBlancos ob)
    {
        JOptionPane.showInternalMessageDialog(jDesktopPane1,ob.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
    }

    catch(NumberFormatException ob)
       {
        JOptionPane.showInternalMessageDialog(jDesktopPane1,"Entre solo numeros.","ERROR",JOptionPane.ERROR_MESSAGE);

       }
    catch(Exception e)
    {
       JOptionPane.showInternalMessageDialog(jDesktopPane1," Verifique los datos: Error en la conexión","ERROR",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1MouseReleased

    private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
        // TODO add your handling code here:
         jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1MouseReleased

    private void jMenuItem2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseReleased
        // TODO add your handling code here:
        jInternalFrame2.setVisible(true);




    }//GEN-LAST:event_jMenuItem2MouseReleased

    private void jMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseReleased
        // TODO add your handling code here:
       //jMenuItem1.setEnabled(false);
    }//GEN-LAST:event_jMenu1MouseReleased

    private void jInternalFrame2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jInternalFrame2ComponentShown
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jInternalFrame2ComponentShown

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:
try{
        Element  d =obj.BD();
             int aaaaa=d.getContentSize();
             List q=d.getChildren();
             Element nn=(Element)q.get(0);
             jTextArea1.append("<?xml version="+"1.0"+" encoding="+"utf-8?>\n");
             jTextArea1.append("< "+"database  "+"' "+obj.getNBD()+" '"+" >\n");
            Iterator i=q.iterator();
             while(i.hasNext())
             {
                 Element w=(Element)i.next();

                 jTextArea1.append("                < "+w.getName()+" name "+"' "+w.getAttributeValue("name")+" '"+" >\n");
                  jTextArea1.append(" ");
                 List q1=w.getChildren();
                   Iterator k=q1.iterator();
                   Element ps=null;
                   jTextArea1.append("\t<structure>\n");
                   while(k.hasNext())
                   {
                       ps=(Element)k.next();
                       List q3=ps.getChildren("row");
                      
                        Iterator j=q3.iterator();
                         while(j.hasNext())
                         {
                          jTextArea1.append("");
                          Element aa=(Element)j.next();
                          List at=aa.getAttributes();
                              Iterator x=at.iterator();
                              String dd =" ";
                              dd+="\t\t<field";
                              while(x.hasNext())
                              {
                                Attribute hh=(Attribute)x.next();
                                 String Cnom=hh.getName();
                                 String Cval=hh.getValue();
                                  if(Cnom.compareTo("Key")==0 && Cval.compareTo("PRI")==0)
                                  {
                                    Cval="PRIMARI"; 
                                    dd+=" ";
                                    dd+=Cnom;
                                    dd+=" ";
                                    dd+="'"+Cval+"'";
                                    dd+=" ";
                                  }else
                                       if(Cnom.compareTo("Key")==0 && Cval.compareTo("MUL")==0)
                                       {
                                         Cval="FORANGE"; 
                                         dd+=" ";
                                         dd+=Cnom;
                                         dd+=" ";
                                         dd+="'"+Cval+"'";
                                         dd+=" ";
                                       }
                                       else
                                          {
                                           dd+=" ";
                                           dd+=Cnom;
                                           dd+=" ";
                                           dd+="'"+Cval+"'";
                                           dd+=" ";
                                          }
                                
                               
                              }
                              dd+="/>";

                              jTextArea1.append(" "+dd+"\n");
                              //jTextArea1.append("");
                          
                         }
                       
                        
                   }
                   jTextArea1.append("\t</structure>\n");

                   List dd3=ps.getChildren("row1");
                       Iterator jd= dd3.iterator();
                       
                       jTextArea1.append("\t<data>\n");
                        while(jd.hasNext())
                        {
                            Element hh=(Element)jd.next();
                            List ddd=hh.getAttributes();
                            Iterator clau=ddd.iterator();
                            String jor="";
                            jor+="\t\t<row";
                              while(clau.hasNext())
                              {
                                  Attribute vval=(Attribute)clau.next();
                                  jor+=" ";
                                  jor+=vval.getName();
                                  jor+=" ";
                                  jor+=vval.getValue();
                                  jor+=" ";
                              }
                            jor+="/>";
                            jTextArea1.append(" "+jor+"\n");
                        }



                   jTextArea1.append("\t</data>\n");


                   jTextArea1.append("           </table>\n");
             }
          jTextArea1.append("</"+"database "+">\n");
}  catch(Exception e)
  {
    jTextArea1.append("Error :" +e.getMessage());
  }
jButton5.setEnabled(true);
    }//GEN-LAST:event_jButton3MouseReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        // TODO add your handling code here:
       try{
        String bd=(String)jComboBox1.getSelectedItem();
        obj.setnomBD(bd);
        obj.setConBD();
        obj.Conectar2();
        jInternalFrame2.setVisible(true);
        jInternalFrame3.setVisible(false);
       }catch(Exception e)
                  {
                    System.out.print("Error :"+e.getMessage());
                  }
    }//GEN-LAST:event_jButton4MouseReleased

    private void jInternalFrame3ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jInternalFrame3ComponentHidden
        // TODO add your handling code here:
        jMenu1.setEnabled(true);
    }//GEN-LAST:event_jInternalFrame3ComponentHidden

    private void jInternalFrame3InternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame3InternalFrameActivated
        // TODO add your handling code here:
        jMenu1.setEnabled(false);
    }//GEN-LAST:event_jInternalFrame3InternalFrameActivated

    private void jInternalFrame2InternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame2InternalFrameActivated
        // TODO add your handling code here:
        jMenu1.setEnabled(false);
    }//GEN-LAST:event_jInternalFrame2InternalFrameActivated

    private void jInternalFrame2ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jInternalFrame2ComponentHidden
        // TODO add your handling code here:
        jMenu1.setEnabled(true);
    }//GEN-LAST:event_jInternalFrame2ComponentHidden

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        // TODO add your handling code here:
        jTextArea1.setText(" ");
        obj.setnomBD(" ");
        
        jButton5.setEnabled(false);
        jInternalFrame3.setVisible(true);
        jInternalFrame2.setVisible(false);
    }//GEN-LAST:event_jButton6MouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
